### ISSUE TITLE
Add Favicon 

### ISSUE THREAD

**Issue by lonewolf235** [Diversion2k22/Bashinda#2]
Add Favicons to the main and all the sub-websites

**Comment by MThabsheer7** [comment]
Hey there, I can do this. Can you tell me which icon do you need for favicon?

**Comment by lonewolf235** [comment]
> Hey @lonewolf235 , I can do this. Can you tell me which icon do you need for favicon?

Hey @MThabsheer7 , are you a part of Bashinda project in diversion event, if yes, may I know your real name?

**Comment by npkeerthi** [comment]
@MThabsheer7 May I get This done?
if Im not a part of this project ?

**Comment by MThabsheer7** [comment]
@lonewolf235 No I'm not.
